### ISSUE TITLE
postgresql数据库表主键无法读取

### ISSUE THREAD

**Issue by cookies0824** [tswine/tswine-jdbc#1]
>>01:07:53:调用方法抛出了异常(NATIVE_CALL_EXCEPTION):strutil.length 位于50行 资源:/templates/mapper.xml.btl
调用方法出错 strutil.length
47|        for(field in table.primaryKeys){
48|            primaryKeyParam += "and " + field.columnName +" = #{"+ field.fieldName+"} ";
49|        }
50|        if(strutil.length(primaryKeyParam) >= 3){
51|            primaryKeyParam = strutil.subString(primaryKeyParam,3);
52|        }
53|     %>
2019-08-15 13:07:53 INFO  AbstractTemplateEngine:123 - 生成mapper接口:E:\IdeaProjects\tswine-jdbc-master\tswine-jdbc-test\src\main\java\cn\tswine\jdbc\test\generator\mapper\CoreConfigJobNumberMapper.java
java.lang.NullPointerException: Error:length(null)
	at org.beetl.ext.fn.StringUtil.length(StringUtil.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.beetl.core.fun.ObjectUtil.invoke(ObjectUtil.java:386)
	at org.beetl.core.fun.ObjectUtil.invoke(ObjectUtil.java:345)
	at org.beetl.core.fun.ObjectUtil.invokeObject(ObjectUtil.java:370)
	at org.beetl.core.fun.SingleFunctionWrapper.call(SingleFunctionWrapper.java:64)
	at org.beetl.core.statement.FunctionExpression.evaluate(FunctionExpression.java:83)
	at org.beetl.core.statement.CompareExpression.evaluate(CompareExpression.java:61)
	at org.beetl.core.statement.IfStatement.execute(IfStatement.java:55)
	at org.beetl.core.statement.Program.run(Program.java:69)
	at org.beetl.core.statement.Program.execute(Program.java:61)
	at org.beetl.core.Template.renderTo(Template.java:143)
	at org.beetl.core.Template.renderTo(Template.java:103)
	at cn.tswine.jdbc.generator.engine.BeetlTemplateEngine.writer(BeetlTemplateEngine.java:45)
	at cn.tswine.jdbc.generator.engine.AbstractTemplateEngine.generatorMapper(AbstractTemplateEngine.java:118)
	at cn.tswine.jdbc.generator.engine.AbstractTemplateEngine.batchGenerator(AbstractTemplateEngine.java:83)
	at cn.tswine.jdbc.generator.CodeGenerator.execute(CodeGenerator.java:73)
	at cn.tswine.jdbc.test.generator.CodeGeneratorPostgreSqlTest.execute(CodeGeneratorPostgreSqlTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
java.lang.NullPointerException: Error:length(null)
	at org.beetl.ext.fn.StringUtil.length(StringUtil.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.beetl.core.fun.ObjectUtil.invoke(ObjectUtil.java:386)
	at org.beetl.core.fun.ObjectUtil.invoke(ObjectUtil.java:345)
	at org.beetl.core.fun.ObjectUtil.invokeObject(ObjectUtil.java:370)
	at org.beetl.core.fun.SingleFunctionWrapper.call(SingleFunctionWrapper.java:64)
	at org.beetl.core.statement.FunctionExpression.evaluate(FunctionExpression.java:83)
	at org.beetl.core.statement.CompareExpression.evaluate(CompareExpression.java:61)
	at org.beetl.core.statement.IfStatement.execute(IfStatement.java:55)
	at org.beetl.core.statement.Program.run(Program.java:69)
	at org.beetl.core.statement.Program.execute(Program.java:61)
	at org.beetl.core.Template.renderTo(Template.java:143)
	at org.beetl.core.Template.renderTo(Template.java:103)
	at cn.tswine.jdbc.generator.engine.BeetlTemplateEngine.writer(BeetlTemplateEngine.java:45)
	at cn.tswine.jdbc.generator.engine.AbstractTemplateEngine.generatorMapper(AbstractTemplateEngine.java:129)
	at cn.tswine.jdbc.generator.engine.AbstractTemplateEngine.batchGenerator(AbstractTemplateEngine.java:83)
	at cn.tswine.jdbc.generator.CodeGenerator.execute(CodeGenerator.java:73)
	at cn.tswine.jdbc.test.generator.CodeGeneratorPostgreSqlTest.execute(CodeGeneratorPostgreSqlTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
>>01:07:53:调用方法抛出了异常(NATIVE_CALL_EXCEPTION):strutil.length 位于33行 资源:/templates/mapper.interface.java.btl
调用方法出错 strutil.length
30|        for(field in table.primaryKeys){
31|            primaryKeyParam += ",@Param(\""+field.fieldName+"\") "+ field.fieldType.type +" "+field.fieldName;
32|        }
33|        if(strutil.length(primaryKeyParam) >=1 ){
34|           primaryKeyParam = strutil.subString(primaryKeyParam,1);
35|        }
36|    %>
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
2019-08-15 13:07:53 INFO  CodeGenerator:74 - 代码生成完毕

**Comment by tswine** [comment]
为实现postgres数据库主键判断的方法无法获取主键，则主键集合为空，遍历的时候报空指针异常，已在最新的代码中修复
